steps:
    - name: "gcr.io/cloud-builders/docker"
      args:
          [
              "build",
              "--build-arg",
              "DB_HOST",
              "--build-arg",
              "DB_PORT",
              "--build-arg",
              "DB_USERNAME",
              "--build-arg",
              "DB_PASSWORD",
              "--build-arg",
              "DB_DATABASE",
              "-f",
              "Dockerfile",
              "-t",
              "gcr.io/${PROJECT_ID}/x1000-exchange-stag:$SHORT_SHA",
              ".",
          ]
      secretEnv:
          ["DB_HOST", "DB_PORT", "DB_USERNAME", "DB_PASSWORD", "DB_DATABASE"]
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/${PROJECT_ID}/x1000-exchange-stag:$SHORT_SHA"]
    - name: "gcr.io/cloud-builders/gcloud"
      id: create-instance-template
      args:
          - compute
          - instance-templates
          - create-with-container
          - x1000-exchange-stag-t-v1-$_ENV-$BUILD_ID
          - --custom-cpu=1
          - --custom-memory=4GB
          - --boot-disk-size=20GB
          - --region=us-central1
          - --subnet=default
          - --tags=allow-hc-and-proxy,allow-ssh,allow-http,allow-https,allow-5432-tcp
          - --container-image
          - gcr.io/${PROJECT_ID}/x1000-exchange-stag:$SHORT_SHA
    - name: "gcr.io/cloud-builders/gcloud"
      entrypoint: "bash"
      args: [
              "-c",
              "gcloud compute instance-groups managed rolling-action
              start-update x1000-exchange-stag-mig
              --version=template=x1000-exchange-stag-t-v1-$_ENV-$BUILD_ID
              --region=us-central1 --max-unavailable=0",
          ]

availableSecrets:
    secretManager:
        - versionName: projects/${PROJECT_ID}/secrets/SOCIAL_FI_DB_HOST/versions/latest
          env: DB_HOST
        - versionName: projects/${PROJECT_ID}/secrets/SOCIAL_FI_DB_PORT/versions/latest
          env: DB_PORT
        - versionName: projects/${PROJECT_ID}/secrets/SOCIAL_FI_DB_USERNAME/versions/latest
          env: DB_USERNAME
        - versionName: projects/${PROJECT_ID}/secrets/SOCIAL_FI_DB_PASSWORD/versions/latest
          env: DB_PASSWORD
        - versionName: projects/${PROJECT_ID}/secrets/X1000_EXCHANGE_DB_DATABASE/versions/latest
          env: DB_DATABASE
